services:
  db:
    image: postgres:17.0
    hostname: ${DATABASE_HOST}
    ports:
      - '5432:${DATABASE_PORT}'
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
