/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as GamesUrlRouteImport } from './routes/games/url'
import { Route as GamesEmailRouteImport } from './routes/games/email'
import { Route as MarketingResourcesRouteImport } from './routes/_marketing/resources'
import { Route as MarketingProductsRouteImport } from './routes/_marketing/products'
import { Route as MarketingPricingRouteImport } from './routes/_marketing/pricing'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesUrlRoute = GamesUrlRouteImport.update({
  id: '/games/url',
  path: '/games/url',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesEmailRoute = GamesEmailRouteImport.update({
  id: '/games/email',
  path: '/games/email',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingResourcesRoute = MarketingResourcesRouteImport.update({
  id: '/_marketing/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingProductsRoute = MarketingProductsRouteImport.update({
  id: '/_marketing/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingPricingRoute = MarketingPricingRouteImport.update({
  id: '/_marketing/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pricing': typeof MarketingPricingRoute
  '/products': typeof MarketingProductsRoute
  '/resources': typeof MarketingResourcesRoute
  '/games/email': typeof GamesEmailRoute
  '/games/url': typeof GamesUrlRoute
  '/auth/': typeof AuthIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pricing': typeof MarketingPricingRoute
  '/products': typeof MarketingProductsRoute
  '/resources': typeof MarketingResourcesRoute
  '/games/email': typeof GamesEmailRoute
  '/games/url': typeof GamesUrlRoute
  '/auth': typeof AuthIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_marketing/pricing': typeof MarketingPricingRoute
  '/_marketing/products': typeof MarketingProductsRoute
  '/_marketing/resources': typeof MarketingResourcesRoute
  '/games/email': typeof GamesEmailRoute
  '/games/url': typeof GamesUrlRoute
  '/auth/': typeof AuthIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/pricing'
    | '/products'
    | '/resources'
    | '/games/email'
    | '/games/url'
    | '/auth/'
    | '/dashboard/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/pricing'
    | '/products'
    | '/resources'
    | '/games/email'
    | '/games/url'
    | '/auth'
    | '/dashboard'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/_marketing/pricing'
    | '/_marketing/products'
    | '/_marketing/resources'
    | '/games/email'
    | '/games/url'
    | '/auth/'
    | '/dashboard/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MarketingPricingRoute: typeof MarketingPricingRoute
  MarketingProductsRoute: typeof MarketingProductsRoute
  MarketingResourcesRoute: typeof MarketingResourcesRoute
  GamesEmailRoute: typeof GamesEmailRoute
  GamesUrlRoute: typeof GamesUrlRoute
  AuthIndexRoute: typeof AuthIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/url': {
      id: '/games/url'
      path: '/games/url'
      fullPath: '/games/url'
      preLoaderRoute: typeof GamesUrlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/email': {
      id: '/games/email'
      path: '/games/email'
      fullPath: '/games/email'
      preLoaderRoute: typeof GamesEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing/resources': {
      id: '/_marketing/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof MarketingResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing/products': {
      id: '/_marketing/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof MarketingProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing/pricing': {
      id: '/_marketing/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof MarketingPricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MarketingPricingRoute: MarketingPricingRoute,
  MarketingProductsRoute: MarketingProductsRoute,
  MarketingResourcesRoute: MarketingResourcesRoute,
  GamesEmailRoute: GamesEmailRoute,
  GamesUrlRoute: GamesUrlRoute,
  AuthIndexRoute: AuthIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
