/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as HomeRouteImport } from './routes/_home'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as HomeIndexRouteImport } from './routes/_home/index'
import { Route as ProtectedDashboardIndexRouteImport } from './routes/_protected/dashboard/index'
import { Route as AuthSignupIndexRouteImport } from './routes/_auth/signup/index'
import { Route as AuthLoginIndexRouteImport } from './routes/_auth/login/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ProtectedDashboardTeamRouteImport } from './routes/_protected/dashboard/team'
import { Route as ProtectedDashboardScheduleRouteImport } from './routes/_protected/dashboard/schedule'
import { Route as HomeGamesUrlRouteImport } from './routes/_home/games/url'
import { Route as HomeGamesEmailRouteImport } from './routes/_home/games/email'
import { Route as HomeMarketingResourcesRouteImport } from './routes/_home/_marketing/resources'
import { Route as HomeMarketingPricingRouteImport } from './routes/_home/_marketing/pricing'
import { Route as HomeMarketingImpactRouteImport } from './routes/_home/_marketing/impact'

const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/_home',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HomeRoute,
} as any)
const ProtectedDashboardIndexRoute = ProtectedDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => ProtectedRoute,
} as any)
const AuthSignupIndexRoute = AuthSignupIndexRouteImport.update({
  id: '/signup/',
  path: '/signup/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => AuthRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedDashboardTeamRoute = ProtectedDashboardTeamRouteImport.update({
  id: '/dashboard/team',
  path: '/dashboard/team',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedDashboardScheduleRoute =
  ProtectedDashboardScheduleRouteImport.update({
    id: '/dashboard/schedule',
    path: '/dashboard/schedule',
    getParentRoute: () => ProtectedRoute,
  } as any)
const HomeGamesUrlRoute = HomeGamesUrlRouteImport.update({
  id: '/games/url',
  path: '/games/url',
  getParentRoute: () => HomeRoute,
} as any)
const HomeGamesEmailRoute = HomeGamesEmailRouteImport.update({
  id: '/games/email',
  path: '/games/email',
  getParentRoute: () => HomeRoute,
} as any)
const HomeMarketingResourcesRoute = HomeMarketingResourcesRouteImport.update({
  id: '/_marketing/resources',
  path: '/resources',
  getParentRoute: () => HomeRoute,
} as any)
const HomeMarketingPricingRoute = HomeMarketingPricingRouteImport.update({
  id: '/_marketing/pricing',
  path: '/pricing',
  getParentRoute: () => HomeRoute,
} as any)
const HomeMarketingImpactRoute = HomeMarketingImpactRouteImport.update({
  id: '/_marketing/impact',
  path: '/impact',
  getParentRoute: () => HomeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof HomeIndexRoute
  '/impact': typeof HomeMarketingImpactRoute
  '/pricing': typeof HomeMarketingPricingRoute
  '/resources': typeof HomeMarketingResourcesRoute
  '/games/email': typeof HomeGamesEmailRoute
  '/games/url': typeof HomeGamesUrlRoute
  '/dashboard/schedule': typeof ProtectedDashboardScheduleRoute
  '/dashboard/team': typeof ProtectedDashboardTeamRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/login/': typeof AuthLoginIndexRoute
  '/signup/': typeof AuthSignupIndexRoute
  '/dashboard/': typeof ProtectedDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof HomeIndexRoute
  '/impact': typeof HomeMarketingImpactRoute
  '/pricing': typeof HomeMarketingPricingRoute
  '/resources': typeof HomeMarketingResourcesRoute
  '/games/email': typeof HomeGamesEmailRoute
  '/games/url': typeof HomeGamesUrlRoute
  '/dashboard/schedule': typeof ProtectedDashboardScheduleRoute
  '/dashboard/team': typeof ProtectedDashboardTeamRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/login': typeof AuthLoginIndexRoute
  '/signup': typeof AuthSignupIndexRoute
  '/dashboard': typeof ProtectedDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_home': typeof HomeRouteWithChildren
  '/_protected': typeof ProtectedRouteWithChildren
  '/_home/': typeof HomeIndexRoute
  '/_home/_marketing/impact': typeof HomeMarketingImpactRoute
  '/_home/_marketing/pricing': typeof HomeMarketingPricingRoute
  '/_home/_marketing/resources': typeof HomeMarketingResourcesRoute
  '/_home/games/email': typeof HomeGamesEmailRoute
  '/_home/games/url': typeof HomeGamesUrlRoute
  '/_protected/dashboard/schedule': typeof ProtectedDashboardScheduleRoute
  '/_protected/dashboard/team': typeof ProtectedDashboardTeamRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_auth/login/': typeof AuthLoginIndexRoute
  '/_auth/signup/': typeof AuthSignupIndexRoute
  '/_protected/dashboard/': typeof ProtectedDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/impact'
    | '/pricing'
    | '/resources'
    | '/games/email'
    | '/games/url'
    | '/dashboard/schedule'
    | '/dashboard/team'
    | '/api/auth/$'
    | '/login/'
    | '/signup/'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/impact'
    | '/pricing'
    | '/resources'
    | '/games/email'
    | '/games/url'
    | '/dashboard/schedule'
    | '/dashboard/team'
    | '/api/auth/$'
    | '/login'
    | '/signup'
    | '/dashboard'
  id:
    | '__root__'
    | '/_auth'
    | '/_home'
    | '/_protected'
    | '/_home/'
    | '/_home/_marketing/impact'
    | '/_home/_marketing/pricing'
    | '/_home/_marketing/resources'
    | '/_home/games/email'
    | '/_home/games/url'
    | '/_protected/dashboard/schedule'
    | '/_protected/dashboard/team'
    | '/api/auth/$'
    | '/_auth/login/'
    | '/_auth/signup/'
    | '/_protected/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  HomeRoute: typeof HomeRouteWithChildren
  ProtectedRoute: typeof ProtectedRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_home': {
      id: '/_home'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_home/': {
      id: '/_home/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof HomeRoute
    }
    '/_protected/dashboard/': {
      id: '/_protected/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof ProtectedDashboardIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_auth/signup/': {
      id: '/_auth/signup/'
      path: '/signup'
      fullPath: '/signup/'
      preLoaderRoute: typeof AuthSignupIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login/': {
      id: '/_auth/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/dashboard/team': {
      id: '/_protected/dashboard/team'
      path: '/dashboard/team'
      fullPath: '/dashboard/team'
      preLoaderRoute: typeof ProtectedDashboardTeamRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/dashboard/schedule': {
      id: '/_protected/dashboard/schedule'
      path: '/dashboard/schedule'
      fullPath: '/dashboard/schedule'
      preLoaderRoute: typeof ProtectedDashboardScheduleRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_home/games/url': {
      id: '/_home/games/url'
      path: '/games/url'
      fullPath: '/games/url'
      preLoaderRoute: typeof HomeGamesUrlRouteImport
      parentRoute: typeof HomeRoute
    }
    '/_home/games/email': {
      id: '/_home/games/email'
      path: '/games/email'
      fullPath: '/games/email'
      preLoaderRoute: typeof HomeGamesEmailRouteImport
      parentRoute: typeof HomeRoute
    }
    '/_home/_marketing/resources': {
      id: '/_home/_marketing/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof HomeMarketingResourcesRouteImport
      parentRoute: typeof HomeRoute
    }
    '/_home/_marketing/pricing': {
      id: '/_home/_marketing/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof HomeMarketingPricingRouteImport
      parentRoute: typeof HomeRoute
    }
    '/_home/_marketing/impact': {
      id: '/_home/_marketing/impact'
      path: '/impact'
      fullPath: '/impact'
      preLoaderRoute: typeof HomeMarketingImpactRouteImport
      parentRoute: typeof HomeRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
  AuthSignupIndexRoute: typeof AuthSignupIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginIndexRoute: AuthLoginIndexRoute,
  AuthSignupIndexRoute: AuthSignupIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface HomeRouteChildren {
  HomeIndexRoute: typeof HomeIndexRoute
  HomeMarketingImpactRoute: typeof HomeMarketingImpactRoute
  HomeMarketingPricingRoute: typeof HomeMarketingPricingRoute
  HomeMarketingResourcesRoute: typeof HomeMarketingResourcesRoute
  HomeGamesEmailRoute: typeof HomeGamesEmailRoute
  HomeGamesUrlRoute: typeof HomeGamesUrlRoute
}

const HomeRouteChildren: HomeRouteChildren = {
  HomeIndexRoute: HomeIndexRoute,
  HomeMarketingImpactRoute: HomeMarketingImpactRoute,
  HomeMarketingPricingRoute: HomeMarketingPricingRoute,
  HomeMarketingResourcesRoute: HomeMarketingResourcesRoute,
  HomeGamesEmailRoute: HomeGamesEmailRoute,
  HomeGamesUrlRoute: HomeGamesUrlRoute,
}

const HomeRouteWithChildren = HomeRoute._addFileChildren(HomeRouteChildren)

interface ProtectedRouteChildren {
  ProtectedDashboardScheduleRoute: typeof ProtectedDashboardScheduleRoute
  ProtectedDashboardTeamRoute: typeof ProtectedDashboardTeamRoute
  ProtectedDashboardIndexRoute: typeof ProtectedDashboardIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedDashboardScheduleRoute: ProtectedDashboardScheduleRoute,
  ProtectedDashboardTeamRoute: ProtectedDashboardTeamRoute,
  ProtectedDashboardIndexRoute: ProtectedDashboardIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  HomeRoute: HomeRouteWithChildren,
  ProtectedRoute: ProtectedRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
